### ISSUE TITLE
Query regarding the drug dealer location

### ISSUE THREAD

**Issue by bakerzone** [qbcore-framework/qb-coke#3]
Hiya,

I'm wondering if you could let me know how the dealer side of the script works, it seems to look at the opening times as per another script of the same sort of function, but I cannot see where this is looked up in a database in anyway.

Can you give me a few pointer where the door is that you knock on.

Thanks

**Comment by BerkieBb** [comment]
It should be in the dealers table in your database but standard there is no set-up, you have to set it up using the /createdealer command
