### ISSUE TITLE
Unable to sell coke

### ISSUE THREAD

**Issue by bakerzone** [qbcore-framework/qb-coke#4]
Hi,

I asked a question a few days ago and you advised to add a new dealer via the newdealer command, this does create a dealer but that is only used for the qb-drugs script and it never offers the ability to sell coke, it only shows the missions and to buy weed.

If I remove the deliveries part of qb-drugs then you cannot create dealers, so the register command is lost as that script is no longer being loaded to be used.

Is there a way to sell coke via this script or is it best to write one myself or adapt one that is already used for sell weed?

Thanks
Angie

**Comment by GhzGarage** [comment]
Been added to cornerselling
